[package]
name = "nota"
version = "0.1.0"
authors = ["LudeeD <luiscomsnofim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
log = "0.4.8"
simple_logger = "1.6.0"
serde = {version = "1.0.106", features = ["derive"]}
toml = "0.5.6"
bincode = "1.2.1"
comrak = "0.7"
handlebars = "3.0.1"
