[package]
name = "nota"
version = "0.1.0"
authors = ["LudeeD <luiscomsnofim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
simple_logger = "1.6.0"
serde = {version = "1.0.106", features = ["derive"]}
serde_json = "1.0"
bincode = "1.2.1"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
handlebars = "3.0.1"
